### PR TITLE
Reinstate changes from #6

### PR DESCRIPTION
**Pull request by zbrachinara**
Adds the changes from #6 back in after they were lost in the whole-file refactor in #5

### CODE REVIEW

**Comment by vacuus** [comment]
Wow, time really flies. This was really opened 7 months ago?

**Comment by icanc0** [comment]
No way, thats fr bussin no cap crazy!!!

**Comment by zbrachinara** [comment]
It's been way too long, do we even still know if this works?

**Comment by icanc0** [comment]
web development moment 💀

**Comment by DefyGG** [comment]
No clue :)

**Pull request merged**
