### PR TITLE
refactor, reformat, fix shit code by bric.

### PR DESCRIPTION
**Pull request by icanc0**
thanks bric

### CODE REVIEW

**Comment by zbrachinara** [comment]
thanks bincent

On a more serious note, this is a person that I know also in montgomery county.

**Comment by DefyGG** [comment]
Hey lol, what did you change in the program?

**Comment by icanc0** [comment]
when the 💀

**Comment by zbrachinara** [comment]
From what I've reviewed, these are the changes in this pr:
* Moved function definitions out of the single main function (my interpretation is that this lets you test code in the browser console)
* Fixed my horrible async/await notation
* Reformatted everything consistently with 8-spaced tabs

**Review by DefyGG — APPROVED** [review]
Alright, looks good! I'm going to have to properly merge the previous commit and this one. But thanks!

**Comment by DefyGG** [comment]
Also btw most of the horrible function organization is my fault. I was in a rush when making this originally, so I kinda pretended that "good" code wasn't a thing (its a miracle I  named variables decent enough and didn't go with the classic "x", "y", "z", "test", "test1").

**Pull request merged**
